### ISSUE TITLE
Emacs fails to display screen on graphics

### ISSUE THREAD

**Issue by iwahbe** [remacs/remacs#1533]
<img width="748" alt="Screen Shot 2019-08-04 at 10 08 55 PM" src="https://user-images.githubusercontent.com/22222529/62440340-8aec3980-b704-11e9-9ed9-37dfa7e3ed8b.png">

I did my first load and build following the given instructions:
$ brew install gnutls texinfo autoconf
$ ./autogen.sh
$ ./configure --enable-rust-debug
$ make
$ RUST_BACKTRACE=1 src/remacs -q

I didn't see any error messages, but I only get the blank screen. The graphics window is responsive. I can do things like `M-x` and the top of the screen changes from`*GNU Emacs*` to `*Minibuf-1*`. The scroll bars appear and scroll, and I can use them to derive I can split windows using `M-x 2` and `M-x 3`.
I have not seen a working version, so I can't give a full repo. I'm running a 2016 13-inch mac book pro on macOS Mojave 10.14.5 (18F132). I would be happy to provide any other info, if requested.

**Comment by shaleh** [comment]
to test safely it is `src/remacs -Q` that is a capital `Q` not a lower case `q`.

I just did a build on 10.13.6 all is well here. We had issues on Mojave a little while back but I thought they were resolved.

**Comment by iwahbe** [comment]
I just repeated the test with `src/remacs -Q`. I got the same result.

**Comment by benreyn** [comment]
I am getting the same thing on my local build. I can run elisp in batch mode but there is no display.

**Comment by shaleh** [comment]
Grumble. Looks like we need to do something for the current MacOS. I have avoid upgrading due to work apps as well.

**Comment by scoiatael** [comment]
FYI there's no problem with upstream as of https://github.com/emacs-mirror/emacs/commit/da0f8dbf8fea53da65d1990b3f9f235e4fe3f9e0 - the weird thing is there's nothing in logs nor trace. I'll try merging upstream locally and see if that helps :)

**Comment by darrenkenny** [comment]
I'm seeing this too, and it looks very similar to the issue #895 too, which was meant to have been fixed, but seems to be back again.

I am seeing this on macOS 10.14.6 and using the latest master branch as of Dec 13.

**Comment by skoji** [comment]
Same here with macOS 10.15.2 using latest master (239a4fb305cbe1b015f16788e0502461166b03c8).

**Comment by shaleh** [comment]
I have started work on what is turning out to be a massive PR that will bring us towards the top of Emacs 26. I am not sure yet how to break it up into manageable pieces. I might post the whole thing and we can all find a way to make it work.

**Comment by r4ravi2008** [comment]
still facing he same issue, any update on this?

**Comment by r4ravi2008** [comment]
For anyone still having this issue, starting like this in terminal works fine for me:
`src/remacs -nw`
I am using doom config with remacs and it works too..

**Comment by shaleh** [comment]
There are fixes we have not been able to port to remacs yet. Sorry for the frustration.
